'use strict';

var gulp = require('gulp');
var tap = require('gulp-tap');
var rename = require('gulp-rename');
var config = require('../../config/breakpoints');
var _ = require('lodash');

var fs = require('fs');
var template = _.template(fs.readFileSync(__dirname + '/template.scss', 'utf8'));

/*******************************************************************************
    BREAKPOINTS TASK
*******************************************************************************/

gulp.task('breakpoints', function() {
  return gulp.src(config.src)
    .pipe(tap(function(file) {

      var data = JSON.parse(file.contents.toString());

      var contents = template({
        breakpoints: data.breakpoints,
        comment: '// DO NOT EDIT THIS FILE DIRECTLY. IT IS CREATED FROM ' + config.src + '\n\n'
      });

      file.contents = new Buffer(contents);

    }))
    .pipe(rename(config.cssName))
    .pipe(gulp.dest(config.dest));
});
