'use strict';

var gulp = require('gulp');
var config = require('../../config/iconfont');
var template = require('gulp-template');
var rename = require('gulp-rename');
var handleErrors = require('../../util/handleErrors');

module.exports = function(glyphs, options) {

  console.log(glyphs, options);

  gulp.src(config.template)
    .pipe(template({
      icons: glyphs.map(function(icon) {
        console.log(icon);

        return {
          name: icon.name,
          // code: icon.codepoint.toString(16)
          code: icon.unicode[0].charCodeAt(0).toString(16)//.toUpperCase()
        };
      }),
      fontName: config.options.fontName,
      fontPath: config.fontPath,
      className: config.className,
      comment: '// DO NOT EDIT DIRECTLY!\n  // Generated by gulp/tasks/iconfont.js\n  // from ' + config.template
    }))
    .on('error', handleErrors)
    .pipe(rename(config.sassOutputName))
    .pipe(gulp.dest(config.sassDest));
};
